### ISSUE TITLE
Tamaño de fuente

### ISSUE THREAD

**Issue by hasbelcaro** [garcialopez/Imprimir-etiquetas-EPL-PHP#1]
Muchas gracias por el aporte, estoy trabajando con una impresora SAT TT448 pero el tamaño del texto es muy grande para la etiqueta, ¿sabes cómo es posible reducir el tamaño de la letra
![WhatsApp Image 2022-05-21 at 8 03 46 PM](https://user-images.githubusercontent.com/7729951/169707209-b1768f3d-e18e-4cac-9990-2484b013ad53.jpeg)
?

**Comment by garcialopez** [comment]
Hola, un gusto en saludarte.

Para el tamaño de la letra puedes echarle un vistazo a los comentarios que inclui en el archivo ImprimirEPL.php<https://github.com/garcialopez/Imprimir-etiquetas-EPL-PHP/blob/master/src/Codadry/JY/Epl/ImprimirEPL.php>:

https://github.com/garcialopez/Imprimir-etiquetas-EPL-PHP/blob/master/src/Codadry/JY/Epl/ImprimirEPL.php

En la línea 145.[cid:f2833cc8-b572-4c06-a890-7312de6c44dc]


________________________________
De: Hasbel Ac ***@***.***>
Enviado: domingo, 22 de mayo de 2022 12:11 p. m.
Para: garcialopez/Imprimir-etiquetas-EPL-PHP ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [garcialopez/Imprimir-etiquetas-EPL-PHP] Tamaño de fuente (Issue #1)


Muchas gracias por el aporte, estoy trabajando con una impresora SAT TT448 pero el tamaño del texto es muy grande para la etiqueta, ¿sabes cómo es posible reducir el tamaño de la letra
[WhatsApp Image 2022-05-21 at 8 03 46 PM]<https://user-images.githubusercontent.com/7729951/169707209-b1768f3d-e18e-4cac-9990-2484b013ad53.jpeg>
?
